from .dashboard         import FlyDashboard
from .legacysource_app  import LegacySourceAdminApp
from .location_app      import LocationAdminApp
from .source_app        import SourceAdminApp
from .specie_app        import SpecieAdminApp
from .fly.fly_list  import FlyAdminApp
from .supplier_app      import SupplierAdminApp
from .group             import GroupAdminApp
from .category import CategoryAdminApp