# Generated by Django 2.2.1 on 2019-05-07 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Fly',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('ccuid', models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='CCU ID')),
                ('entrydate', models.DateTimeField(auto_now_add=True, verbose_name='Entry date')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last update')),
                ('chrx', models.CharField(blank=True, max_length=60, null=True, verbose_name='chrX')),
                ('chry', models.CharField(blank=True, max_length=60, null=True, verbose_name='chrY')),
                ('bal1', models.CharField(blank=True, max_length=60, null=True, verbose_name='bal1')),
                ('chr2', models.CharField(blank=True, max_length=60, null=True, verbose_name='chr2')),
                ('bal2', models.CharField(blank=True, max_length=60, null=True, verbose_name='bal2')),
                ('chr3', models.CharField(blank=True, max_length=60, null=True, verbose_name='chr3')),
                ('bal3', models.CharField(blank=True, max_length=60, null=True, verbose_name='bal3')),
                ('chr4', models.CharField(blank=True, max_length=60, null=True, verbose_name='chr4')),
                ('chru', models.CharField(blank=True, max_length=60, null=True, verbose_name='chrU')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='comments')),
                ('print', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Comment to print')),
                ('loc3_data', models.CharField(blank=True, max_length=30, null=True, verbose_name='Local')),
                ('legacy1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Legacy ID 1')),
                ('legacy2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Legacy ID 2')),
                ('legacy3', models.CharField(blank=True, max_length=30, null=True, verbose_name='Legacy ID 3')),
                ('flydbid', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fly DB ID')),
                ('hospital', models.BooleanField(verbose_name='Hospital')),
                ('died', models.BooleanField(verbose_name='Died')),
                ('loc1_location', models.CharField(blank=True, help_text='<b>Format:</b> Tray_Row_Col &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ( <b>Tray</b> = 1-N <b>Row</b> = A-J <b>Col</b> = 1-10 )', max_length=30, null=True, verbose_name='Chamber location')),
                ('wolbachia', models.BooleanField(verbose_name='Wolbachia')),
                ('last_test', models.DateField(blank=True, null=True, verbose_name='Last test')),
                ('treatment', models.BooleanField(verbose_name='Treatment')),
                ('strain', models.CharField(blank=True, max_length=255, null=True, verbose_name='Strain')),
                ('virus_treatment', models.BooleanField(verbose_name='Virus Treatment')),
                ('last_treatment', models.DateField(blank=True, null=True, verbose_name='Last treatment')),
                ('isogenization', models.BooleanField(verbose_name='Isogenization')),
                ('background', models.CharField(blank=True, max_length=255, null=True, verbose_name='Background')),
                ('generations', models.CharField(blank=True, max_length=255, null=True, verbose_name='#Generations')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flydb.Category')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Ownership')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LegacySource',
            fields=[
                ('legacysource_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('legacysource_name', models.CharField(max_length=30, verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Source legacy',
                'verbose_name_plural': 'Legacy sources',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('location_name', models.CharField(max_length=30, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Care',
                'verbose_name_plural': 'Cares',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('source_name', models.CharField(max_length=30, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('specie_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('specie_name', models.CharField(max_length=100, verbose_name='Name')),
                ('specie_ncbitax', models.IntegerField(blank=True, null=True, verbose_name='NCBITAX')),
            ],
            options={
                'verbose_name': 'Specie',
                'verbose_name_plural': 'Species',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Id')),
                ('supplier_name', models.CharField(max_length=50, verbose_name='Name')),
                ('supplier_contact', models.CharField(blank=True, max_length=30, null=True, verbose_name='Contact')),
                ('supplier_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('supplier_url', models.URLField(blank=True, null=True, verbose_name='Webpage')),
                ('supplier_address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('supplier_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(verbose_name='Begin')),
                ('end', models.DateField(blank=True, null=True, verbose_name='End')),
                ('fly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flydb.Fly')),
            ],
        ),
        migrations.AddField(
            model_name='fly',
            name='legacysource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flydb.LegacySource', verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='fly',
            name='loc2_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loc2_person', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='fly',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flydb.Location', verbose_name='Care'),
        ),
        migrations.AddField(
            model_name='fly',
            name='specie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flydb.Specie'),
        ),
        migrations.CreateModel(
            name='FlyPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewonly', models.BooleanField(verbose_name='Read only access')),
                ('fly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flydb.Fly')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'verbose_name': 'Fly permission',
                'verbose_name_plural': 'Flies permissions',
                'unique_together': {('fly', 'group')},
            },
        ),
    ]
