# Generated by Django 2.2.1 on 2019-05-07 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fly',
            options={'ordering': ['-id'], 'verbose_name': 'Fly stock', 'verbose_name_plural': 'Flies stock'},
        ),
    ]
