# Generated by Django 2.1.7 on 2019-03-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='background',
            field=models.TextField(blank=True, null=True, verbose_name='Background'),
        ),
        migrations.AddField(
            model_name='stock',
            name='generations',
            field=models.TextField(blank=True, null=True, verbose_name='#Generations'),
        ),
        migrations.AddField(
            model_name='stock',
            name='isogenization',
            field=models.BooleanField(default=False, verbose_name='Isogenization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='last_test',
            field=models.DateField(blank=True, null=True, verbose_name='Last test'),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_treatment',
            field=models.DateField(blank=True, null=True, verbose_name='Last treatment'),
        ),
        migrations.AddField(
            model_name='stock',
            name='strain',
            field=models.TextField(blank=True, null=True, verbose_name='Strain'),
        ),
        migrations.AddField(
            model_name='stock',
            name='treatment',
            field=models.TextField(blank=True, null=True, verbose_name='Treatment'),
        ),
        migrations.AddField(
            model_name='stock',
            name='virus_treatment',
            field=models.BooleanField(default=False, verbose_name='Virus Treatment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='wolbachia',
            field=models.BooleanField(default=False, verbose_name='Wolbachia'),
            preserve_default=False,
        ),
    ]
