# Generated by Django 2.2.1 on 2019-05-07 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flydb', '0002_auto_20190507_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fly',
            old_name='loc3_data',
            new_name='external_location',
        ),
        migrations.RemoveField(
            model_name='fly',
            name='entrydate',
        ),
        migrations.RemoveField(
            model_name='fly',
            name='loc1_location',
        ),
        migrations.RemoveField(
            model_name='fly',
            name='loc2_person',
        ),
        migrations.RemoveField(
            model_name='fly',
            name='updated',
        ),
        migrations.AddField(
            model_name='fly',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='fly',
            name='shelf',
            field=models.CharField(blank=True, help_text='Format: Tray_Row_Col ( Tray=1-N; Row=A-J; Col=1-10 )', max_length=30, null=True, verbose_name='Shelf'),
        ),
    ]
