# Generated by Django 2.1.7 on 2019-03-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0002_auto_20190321_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='background',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='generations',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='#Generations'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='strain',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Strain'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='treatment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Treatment'),
        ),
    ]
