# Generated by Django 2.2.1 on 2019-05-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0004_fly_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly',
            name='ccuid',
        ),
        migrations.AddField(
            model_name='fly',
            name='internal_id',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Internal ID'),
        ),
    ]
