# Generated by Django 2.1.7 on 2019-03-21 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flydb.Category'),
        ),
    ]
