# Generated by Django 2.1.7 on 2019-03-21 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0005_stock_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(verbose_name='Begin')),
                ('end', models.DateField(blank=True, null=True, verbose_name='End')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flydb.Stock')),
            ],
        ),
    ]
