# Generated by Django 2.1.7 on 2019-03-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0006_hospitalization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_entrydate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Entry date'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last update'),
        ),
    ]
