# Generated by Django 2.2.1 on 2019-05-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0006_auto_20190511_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='genotype',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Genotype'),
        ),
    ]
