# Generated by Django 2.2.1 on 2019-05-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0007_auto_20190321_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='treatment',
            field=models.BooleanField(verbose_name='Treatment'),
        ),
    ]
