# Generated by Django 2.2.1 on 2019-05-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0007_fly_genotype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly',
            name='shelf',
        ),
        migrations.AddField(
            model_name='fly',
            name='location',
            field=models.CharField(blank=True, help_text='Format: Tray_Row_Col ( Tray=1-N; Row=A-J; Col=1-10 )', max_length=50, null=True, verbose_name='Location'),
        ),
    ]
