# Generated by Django 2.2.1 on 2019-05-06 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('flydb', '0008_auto_20190506_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readonly', models.BooleanField(verbose_name='Read only access')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flydb.Stock')),
            ],
            options={
                'verbose_name': 'Stock permission',
                'verbose_name_plural': 'Stocks permissions',
            },
        ),
    ]
