# Generated by Django 2.2.1 on 2019-05-11 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0008_auto_20190511_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Resposible'),
        ),
    ]
