# Generated by Django 2.2.1 on 2019-05-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0009_stockpermission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockpermission',
            old_name='readonly',
            new_name='viewonly',
        ),
    ]
