# Generated by Django 2.1.8 on 2019-06-11 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0009_auto_20190511_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
