# Generated by Django 2.2.1 on 2019-05-06 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('flydb', '0010_auto_20190506_1421'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockpermission',
            unique_together={('stock', 'group')},
        ),
    ]
