# Generated by Django 2.1.8 on 2019-06-11 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0010_auto_20190611_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specie',
            options={'verbose_name': 'species', 'verbose_name_plural': 'species'},
        ),
    ]
