# Generated by Django 2.2.1 on 2019-05-06 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0011_auto_20190506_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Ownership'),
        ),
    ]
