# Generated by Django 2.2.1 on 2019-05-07 10:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0012_auto_20190506_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
