# Generated by Django 2.1.8 on 2019-06-24 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0016_auto_20190624_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fly',
            old_name='custom_id',
            new_name='internal_id',
        ),
    ]
