# Generated by Django 2.1.8 on 2019-06-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0017_auto_20190624_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='internal_id',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='internal ID'),
        ),
    ]
