# Generated by Django 2.1.8 on 2019-06-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0018_auto_20190624_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='background',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fly',
            name='bal1',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='bal1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fly',
            name='bal2',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='bal2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fly',
            name='bal3',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='bal3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fly',
            name='chr2',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='chr2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fly',
            name='chr3',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='chr3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fly',
            name='chr4',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='chr4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fly',
            name='chru',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='chrU'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fly',
            name='chrx',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='chrX'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fly',
            name='chry',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='chrY'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fly',
            name='comments',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fly',
            name='external_location',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Local'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fly',
            name='generations',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='# generations'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fly',
            name='genotype',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fly',
            name='legacy1',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Legacy ID 1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fly',
            name='legacy2',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Legacy ID 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fly',
            name='legacy3',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Legacy ID 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fly',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Format: Tray_Row_Col ( Tray=1-N; Row=A-J; Col=1-10 )', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fly',
            name='print',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Comment to print'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fly',
            name='strain',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
