# Generated by Django 2.1.8 on 2019-06-24 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0019_auto_20190624_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flydb.Category'),
        ),
    ]
