# Generated by Django 2.1.8 on 2019-06-24 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0021_auto_20190624_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly',
            name='specie',
        ),
        migrations.AddField(
            model_name='fly',
            name='species',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='flydb.Species'),
            preserve_default=False,
        ),
    ]
