# Generated by Django 2.1.8 on 2019-06-24 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0022_auto_20190624_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fly',
            old_name='print',
            new_name='printable_comment',
        ),
    ]
