# Generated by Django 2.1.8 on 2019-06-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0024_auto_20190624_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='line_description',
            field=models.TextField(blank=True),
        ),
    ]
