# Generated by Django 2.1.8 on 2019-06-24 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0025_fly_line_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fly',
            options={'verbose_name': 'fly', 'verbose_name_plural': 'flies'},
        ),
    ]
