# Generated by Django 2.1.8 on 2019-06-24 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0026_auto_20190624_0334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100, verbose_name='source name')),
                ('previous_id', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name': 'origin',
                'verbose_name_plural': 'origins',
                'ordering': ['source'],
            },
        ),
    ]
