# Generated by Django 2.1.8 on 2019-06-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0028_origin_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='origin',
            name='category',
            field=models.CharField(choices=[('center', 'Stock Center'), ('internal', 'Internal Lab'), ('external', 'External Lab')], default='center', max_length=8),
        ),
    ]
