# Generated by Django 2.1.8 on 2019-06-26 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0029_auto_20190624_0346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='origin',
            name='stock',
        ),
        migrations.DeleteModel(
            name='Origin',
        ),
    ]
