# Generated by Django 2.1.8 on 2019-06-26 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0035_stockcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='origin_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fly_stocks', to='flydb.StockCenter'),
        ),
    ]
