# Generated by Django 2.1.8 on 2019-06-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0037_auto_20190626_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fly',
            old_name='origin_name',
            new_name='origin_other',
        ),
    ]
