# Generated by Django 2.1.8 on 2019-06-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0038_auto_20190627_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly',
            name='origin_other',
        ),
        migrations.AddField(
            model_name='fly',
            name='origin_external',
            field=models.CharField(blank=True, max_length=100, verbose_name='lab name'),
        ),
    ]
