# Generated by Django 2.1.8 on 2019-06-27 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190623_2125'),
        ('flydb', '0039_auto_20190627_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='origin_internal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Group', verbose_name='lab name'),
        ),
    ]
