# Generated by Django 2.1.8 on 2019-07-01 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0040_fly_origin_internal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='legacysource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flydb.LegacySource', verbose_name='Source'),
        ),
    ]
