# Generated by Django 2.1.8 on 2019-07-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0041_auto_20190701_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=80, verbose_name='Name'),
        ),
    ]
