# Generated by Django 2.1.8 on 2019-07-03 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0042_auto_20190703_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly',
            name='category',
        ),
    ]
