# Generated by Django 2.1.8 on 2019-07-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0043_remove_fly_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='categories',
            field=models.ManyToManyField(to='flydb.Category'),
        ),
    ]
