# Generated by Django 2.1.8 on 2019-07-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0044_fly_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='special_husbandry_conditions',
            field=models.TextField(blank=True),
        ),
    ]
