# Generated by Django 2.1.8 on 2019-07-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0045_fly_special_husbandry_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='flybase_id',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='FlyBase ID'),
        ),
    ]
