# Generated by Django 2.1.8 on 2019-07-04 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0048_auto_20190704_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='flybase_id',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='FlyBase ID'),
        ),
    ]
