# Generated by Django 2.1.11 on 2019-08-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0050_auto_20190710_1140'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flypermission',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='flypermission',
            name='fly',
        ),
        migrations.RemoveField(
            model_name='flypermission',
            name='group',
        ),
        migrations.DeleteModel(
            name='FlyPermission',
        ),
    ]
