# Generated by Django 2.1.11 on 2019-08-13 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0051_auto_20190813_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='origin_internal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fly_stocks_shared', to='users.Group', verbose_name='lab name'),
        ),
    ]
