# Generated by Django 2.1.11 on 2019-08-13 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0052_auto_20190813_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fly_stocks', to='users.Group'),
        ),
    ]
