# Generated by Django 2.1.11 on 2019-08-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0053_auto_20190813_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly',
            name='wolbachia_strain',
        ),
        migrations.RemoveField(
            model_name='fly',
            name='wolbachia_test_date',
        ),
        migrations.RemoveField(
            model_name='fly',
            name='wolbachia_treatment',
        ),
        migrations.AddField(
            model_name='fly',
            name='wolbachia_treatment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Treatment date'),
        ),
        migrations.AlterField(
            model_name='fly',
            name='wolbachia',
            field=models.BooleanField(default=False, verbose_name='Wolbachia infected'),
        ),
    ]
