# Generated by Django 2.1.11 on 2019-08-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0054_auto_20190813_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='wolbachia_treatment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Wolbachia treatment date'),
        ),
    ]
