# Generated by Django 2.1.11 on 2019-08-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0056_auto_20190813_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly',
            name='background',
        ),
        migrations.RemoveField(
            model_name='fly',
            name='generations',
        ),
        migrations.RemoveField(
            model_name='fly',
            name='isogenization',
        ),
        migrations.AddField(
            model_name='fly',
            name='isogenization_background',
            field=models.CharField(blank=True, max_length=100, verbose_name='Isogenization background'),
        ),
    ]
