# Generated by Django 2.1.11 on 2019-08-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0058_auto_20190813_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalization',
            old_name='end',
            new_name='end_date',
        ),
    ]
