# Generated by Django 2.1.11 on 2019-08-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0059_auto_20190813_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalization',
            old_name='begin',
            new_name='start_date',
        ),
    ]
