# Generated by Django 2.1.11 on 2019-08-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0060_auto_20190813_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalization',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='hospitalization',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
    ]
