# Generated by Django 2.2.10 on 2020-02-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0062_auto_20190909_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='legacysource',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Legacy Source'),
            preserve_default=False,
        ),
    ]
