# Generated by Django 2.2.11 on 2020-03-05 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0063_auto_20200205_1803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LegacySource',
        ),
        migrations.RemoveField(
            model_name='fly',
            name='legacy1',
        ),
        migrations.RemoveField(
            model_name='fly',
            name='legacy2',
        ),
        migrations.RemoveField(
            model_name='fly',
            name='legacy3',
        ),
        migrations.RemoveField(
            model_name='fly',
            name='legacysource',
        ),
    ]
