# Generated by Django 2.2.11 on 2020-03-11 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0064_auto_20200305_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='bal1',
            field=models.CharField(blank=True, max_length=150, verbose_name='Balancer 1'),
        ),
        migrations.AlterField(
            model_name='fly',
            name='bal2',
            field=models.CharField(blank=True, max_length=150, verbose_name='Balancer 2'),
        ),
        migrations.AlterField(
            model_name='fly',
            name='bal3',
            field=models.CharField(blank=True, max_length=150, verbose_name='Balancer 3'),
        ),
        migrations.AlterField(
            model_name='fly',
            name='chr2',
            field=models.CharField(blank=True, max_length=150, verbose_name='Chromosome 2'),
        ),
        migrations.AlterField(
            model_name='fly',
            name='chr3',
            field=models.CharField(blank=True, max_length=150, verbose_name='Chromosome 3'),
        ),
        migrations.AlterField(
            model_name='fly',
            name='chr4',
            field=models.CharField(blank=True, max_length=150, verbose_name='Chromosome 4'),
        ),
        migrations.AlterField(
            model_name='fly',
            name='chru',
            field=models.CharField(blank=True, max_length=150, verbose_name='Unknown genotype'),
        ),
        migrations.AlterField(
            model_name='fly',
            name='chrx',
            field=models.CharField(blank=True, max_length=150, verbose_name='Chromosome X'),
        ),
        migrations.AlterField(
            model_name='fly',
            name='chry',
            field=models.CharField(blank=True, max_length=150, verbose_name='Chromosome Y'),
        ),
    ]
