# Generated by Django 2.2.11 on 2021-03-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flydb', '0065_auto_20200311_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fly',
            options={'permissions': [('can_import', 'Can import from XLSX')]},
        ),
    ]
